language: node_js
node_js:
  - node
before_script:
  - npm install
  - npm install -g gulp
  - gulp
  - npm run cover
after_success:
  - npm run report-coverage
addons:
    code_climate:
        repo_token: 79e8887b60314c6ff14a71a25956794143c4a84991e9148285eda74c57f5b85f