sudo: false
language: node_js
node_js:
  - 0.12.0
  - 4
  - 6
cache:
  directories:
    - node_modules
branches:
  only:
    -master
notifications:
  email: false
before_script:
  - npm install
  - npm install -g gulp
  - npm test
  - gulp